version: "3.9"

services:
  sms-backend:
    build: .
    container_name: sms-backend
    restart: on-failure:2
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /home/ubuntu/test/logs:/app/logs

    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge
